name: Phoenix Docker Release

on:
  release:
    types: [published]

jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release Version
        id: release_version
        uses: battila7/get-version-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/phoenix:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/phoenix:${{ steps.release_version.outputs.version-without-v }}
